import { Theme } from '../../types';

export const musicThemes: Theme[] = [
    {
        id: 'music-sinfonia-mecanica',
        name: 'Sinfonia Mecânica',
        backgroundClass: 'bg-[#1a0f0a]',
        buttonClass: 'bg-[#b87333] text-white hover:bg-[#d4945d] transition-all w-full rounded-none py-4 px-6 flex items-center justify-between font-serif font-black uppercase tracking-tighter',
        buttonHex: '#b87333',
        textHex: '#b87333',
        textClass: 'text-[#b87333] font-serif italic text-3xl font-black uppercase tracking-widest',
        avatarBorder: 'rounded-full border-4 border-[#b87333] p-2 bg-[#1a0f0a]',
        fontFamily: "'Cinzel', serif",
        category: 'music',
        buttonRoundness: 'square',
        isPro: true
    },
    {
        id: 'music-fita-analogica',
        name: 'Fita Analógica',
        backgroundClass: 'bg-[#121212]',
        buttonClass: 'bg-[#262626] text-white border-2 border-white/20 hover:bg-black hover:border-white transition-all w-full rounded-lg py-4 px-6 flex items-center justify-between font-mono font-bold uppercase tracking-widest italic',
        buttonHex: '#ffffff',
        textHex: '#ffffff',
        textClass: 'text-white/80 font-mono tracking-[0.4em] uppercase text-xs font-light',
        avatarBorder: 'rounded-full border border-white/10 p-4 bg-neutral-900',
        fontFamily: "'Courier New', monospace",
        category: 'music',
        buttonRoundness: 'round',
        isPro: false
    },
    {
        id: 'music-sopro-de-ouro',
        name: 'Sopro de Ouro',
        backgroundClass: 'bg-black',
        buttonClass: 'bg-transparent text-[#ffd700] border-2 border-[#ffd700] hover:bg-[#ffd700] hover:text-black transition-all w-full rounded-none py-4 px-10 flex items-center justify-between font-serif uppercase tracking-[0.5em] font-light',
        buttonHex: '#ffd700',
        textHex: '#ffd700',
        textClass: 'text-[#ffd700] font-serif uppercase text-4xl tracking-tighter opacity-80 mix-blend-difference',
        avatarBorder: 'rounded-full border-t border-b border-[#ffd700] p-6',
        fontFamily: "'Playfair Display', serif",
        category: 'music',
        buttonRoundness: 'square',
        isPro: true
    },
    {
        id: 'music-batida-botanica',
        name: 'Batida Botânica',
        backgroundClass: 'bg-[#061c10]',
        buttonClass: 'bg-[#10b981] text-[#061c10] hover:scale-105 transition-transform w-full rounded-3xl py-4 px-6 flex items-center justify-between font-sans font-black uppercase tracking-tight',
        buttonHex: '#10b981',
        textHex: '#10b981',
        textClass: 'text-[#10b981] font-sans font-bold uppercase tracking-widest text-sm',
        avatarBorder: 'rounded-full border-4 border-[#10b981] p-1 bg-[#061c10]',
        fontFamily: "'Inter', sans-serif",
        category: 'music',
        buttonRoundness: 'full',
        isPro: true
    },
    {
        id: 'music-grave-urbano',
        name: 'Grave Urbano',
        backgroundClass: 'bg-[#1c1917]',
        buttonClass: 'bg-[#f97316] text-black hover:bg-orange-600 transition-colors w-full rounded-none py-5 px-6 flex items-center justify-between font-black uppercase italic tracking-tighter',
        buttonHex: '#f97316',
        textHex: '#f97316',
        textClass: 'text-[#f97316] font-black uppercase italic text-5xl tracking-tighter',
        avatarBorder: 'rounded-full border-x-8 border-[#f97316] p-1',
        fontFamily: "'Archivo Black', sans-serif",
        category: 'music',
        buttonRoundness: 'square',
        isPro: true
    },
    {
        id: 'music-hino-de-vitral',
        name: 'Hino de Vitral',
        backgroundClass: 'bg-[#0f172a]',
        buttonClass: 'bg-white/10 backdrop-blur-xl text-white border border-white/30 hover:bg-white/20 transition-all w-full rounded-2xl py-4 px-6 flex items-center justify-between font-serif tracking-widest uppercase',
        buttonHex: '#ffffff',
        textHex: '#ffffff',
        textClass: 'text-white font-serif uppercase tracking-[0.4em] text-center w-full',
        avatarBorder: 'rounded-t-[100px] border-2 border-white/20 p-2 bg-gradient-to-b from-white/10 to-transparent',
        fontFamily: "'Lora', serif",
        category: 'music',
        buttonRoundness: 'rounder',
        isPro: true
    },
    {
        id: 'music-jardim-zen-sonoro',
        name: 'Jardim Zen Sonoro',
        backgroundClass: 'bg-[#e7e5e4]',
        buttonClass: 'bg-[#44403c] text-[#e7e5e4] hover:opacity-90 transition-opacity w-full rounded-full py-4 px-10 flex items-center justify-between font-sans lowercase tracking-tighter',
        buttonHex: '#44403c',
        textHex: '#44403c',
        textClass: 'text-[#44403c] font-sans lowercase font-light text-2xl tracking-[0.2em]',
        avatarBorder: 'rounded-full border border-[#44403c]/10 p-8',
        fontFamily: "'Lexend', sans-serif",
        category: 'music',
        buttonRoundness: 'full',
        isPro: false
    },
    {
        id: 'music-harpa-cosmica',
        name: 'Harpa Cósmica',
        backgroundClass: 'bg-[#020617]',
        buttonClass: 'bg-transparent text-cyan-400 border border-cyan-400/50 hover:bg-cyan-400/10 hover:border-cyan-400 transition-all w-full rounded-full py-4 px-6 flex items-center justify-between font-light tracking-[0.6em] uppercase text-[10px]',
        buttonHex: '#22d3ee',
        textHex: '#ffffff',
        textClass: 'text-white font-thin tracking-[1em] uppercase text-xs opacity-60 italic',
        avatarBorder: 'rounded-full border-t border-cyan-400 p-4 ring-1 ring-cyan-400/20',
        fontFamily: "'Montserrat', sans-serif",
        category: 'music',
        buttonRoundness: 'full',
        isPro: true
    },
    {
        id: 'music-horizonte-neon',
        name: 'Horizonte Neon',
        backgroundClass: 'bg-black',
        buttonClass: 'bg-transparent text-[#f472b6] border-2 border-[#f472b6] hover:bg-[#f472b6] hover:text-black transition-all w-full rounded-none py-4 px-6 flex items-center justify-between font-mono font-black italic uppercase tracking-[0.2em]',
        buttonHex: '#f472b6',
        textHex: '#f472b6',
        textClass: 'text-[#f472b6] font-mono font-black uppercase text-5xl tracking-tighter italic',
        avatarBorder: 'rounded-full border-2 border-[#f472b6] p-2',
        fontFamily: "'Syncopate', sans-serif",
        category: 'music',
        buttonRoundness: 'square',
        isPro: true
    },
    {
        id: 'music-orquestra-origami',
        name: 'Orquestra de Origami',
        backgroundClass: 'bg-[#f5f5f4]',
        buttonClass: 'bg-[#44403c] text-white hover:bg-black transition-all w-full rounded-none py-5 px-6 flex items-center justify-between font-serif font-bold uppercase tracking-widest relative overflow-hidden before:absolute before:inset-0 before:border before:scale-95 before:border-white/20',
        buttonHex: '#44403c',
        textHex: '#44403c',
        textClass: 'text-[#44403c] font-serif uppercase font-black text-3xl tracking-tighter',
        avatarBorder: 'rounded-full border border-[#44403c] p-4 bg-white',
        fontFamily: "'Playfair Display', serif",
        category: 'music',
        buttonRoundness: 'square',
        isPro: true
    }
];
