
import { Theme, FontOption, Product } from './types';
import {
  Mail, Globe, Link as LinkIcon, Phone
} from 'lucide-react';
import {
  SiInstagram, SiFacebook, SiX, SiTiktok, SiThreads, SiLinkedin, SiWhatsapp, SiTelegram,
  SiYoutube, SiTwitch, SiVimeo, SiSpotify, SiSoundcloud, SiApplemusic, SiGithub,
  SiBehance, SiDribbble, SiPinterest, SiDiscord, SiSteam, SiShopee, SiAmazon
} from 'react-icons/si';

export const FONTS: FontOption[] = [
  { name: 'Modern Sans', family: "'Inter', sans-serif", type: 'sans' },
  { name: 'DM Sans', family: "'DM Sans', sans-serif", type: 'sans' },
  { name: 'Geometric', family: "'Poppins', sans-serif", type: 'sans' },
  { name: 'Montserrat', family: "'Montserrat', sans-serif", type: 'sans' },
  { name: 'Tech Outfit', family: "'Outfit', sans-serif", type: 'sans' },
  { name: 'Space Tech', family: "'Space Grotesk', sans-serif", type: 'sans' },
  { name: 'Modern Organic', family: "'Bricolage Grotesque', sans-serif", type: 'sans' },
  { name: 'Art Display', family: "'Syne', sans-serif", type: 'display' },
  { name: 'Classic Serif', family: "'Merriweather', serif", type: 'serif' },
  { name: 'Elegant', family: "'Playfair Display', serif", type: 'serif' },
  { name: 'Soft Serif', family: "'Lora', serif", type: 'serif', isPro: true },
  { name: 'High-End Serif', family: "'Cormorant Garamond', serif", type: 'serif', isPro: true },
  { name: 'Cinzel Decorative', family: "'Cinzel', serif", type: 'display', isPro: true },
  { name: 'Coding Mono', family: "'Fira Code', monospace", type: 'mono', isPro: true },
  { name: 'Bold Impact', family: "'Oswald', sans-serif", type: 'display', isPro: true },
  { name: 'Retro Gamer', family: "'Righteous', cursive", type: 'display', isPro: true },
  { name: 'Impact Title', family: "'Bebas Neue', sans-serif", type: 'display', isPro: true },
  { name: 'Comic Book', family: "'Bangers', system-ui", type: 'display', isPro: true },
  { name: 'Poster', family: "'Abril Fatface', cursive", type: 'display', isPro: true },
  { name: 'Beach Vibe', family: "'Pacifico', cursive", type: 'handwriting', isPro: true },
  { name: '8-Bit Retro', family: "'Press Start 2P', cursive", type: 'display', isPro: true },
  { name: 'Neon Line', family: "'Monoton', display", type: 'display', isPro: true },
  { name: 'Horror Fun', family: "'Creepster', cursive", type: 'display', isPro: true },
  { name: 'Soft Round', family: "'Fredoka', sans-serif", type: 'sans', isPro: true },
  { name: 'Marker Street', family: "'Permanent Marker', cursive", type: 'handwriting', isPro: true },
  { name: 'Fancy Fun', family: "'Lobster', cursive", type: 'display', isPro: true },
  { name: 'Wild Beast', family: "'Rubik Beastly', display", type: 'display', isPro: true },
  { name: 'Highlight Slab', family: "'Zilla Slab Highlight', serif", type: 'serif', isPro: true },
  { name: 'Balloon thick', family: "'Modak', display", type: 'display', isPro: true },
  { name: 'Explosive Fun', family: "'Honk', display", type: 'display', isPro: true },
  { name: 'Editorial Serif', family: "'Caudex', serif", type: 'serif', isPro: true },
  { name: 'Italiana Display', family: "'Italiana', serif", type: 'display', isPro: true },
  { name: 'Indie Variable', family: "'Fraunces', serif", type: 'serif', isPro: true },
  { name: 'Brutalist Mono', family: "'Space Mono', monospace", type: 'mono', isPro: true },
  { name: 'Clean Handwriting', family: "'Shadows Into Light', cursive", type: 'handwriting', isPro: true },
  { name: 'Grunge Style', family: "'Rock Salt', cursive", type: 'handwriting', isPro: true },
  { name: 'Typewriter', family: "'Special Elite', cursive", type: 'mono', isPro: true },
  { name: 'Unbounded Bold', family: "'Unbounded', display", type: 'display', isPro: true },
  { name: 'Neo-Grotesk', family: "'Schibsted Grotesk', sans-serif", type: 'sans', isPro: true },
  { name: 'Liquid Crisis', family: "'Climate Crisis', display", type: 'display', isPro: true },
  { name: 'Isometric Nabla', family: "'Nabla', display", type: 'display', isPro: true },
  { name: 'Drip Puddles', family: "'Rubik Puddles', display", type: 'display', isPro: true },
  { name: 'Dot Matrix', family: "'DotGothic16', monospace", type: 'mono', isPro: true },
  { name: 'CRT Terminal', family: "'VT323', monospace", type: 'mono', isPro: true },
  { name: 'Pixel Game', family: "'Silkscreen', cursive", type: 'display', isPro: true },
  { name: 'Abstract Moirai', family: "'Moirai One', display", type: 'display', isPro: true },
  { name: 'Heavy Bakbak', family: "'Bakbak One', display", type: 'display', isPro: true },
  { name: 'Tech Chakra', family: "'Chakra Petch', sans-serif", type: 'sans', isPro: true },
  { name: 'Space Michroma', family: "'Michroma', sans-serif", type: 'sans', isPro: true },
  { name: 'Fashion Tenor', family: "'Tenor Sans', sans-serif", type: 'sans', isPro: true },
  { name: 'Medieval Display', family: "'Almendra Display', serif", type: 'display', isPro: true },
  { name: 'Fairytale Fun', family: "'Henny Penny', display", type: 'display', isPro: true },
  { name: 'Metal Mania', family: "'Metal Mania', display", type: 'display', isPro: true },
  { name: 'Dripping Horror', family: "'Nosifer', display", type: 'display', isPro: true },
  { name: 'Elegant Script', family: "'Pinyon Script', cursive", type: 'handwriting', isPro: true },
  { name: 'Gothic Fraktur', family: "'UnifrakturMaguntia', serif", type: 'display', isPro: true },
  { name: 'Sci-Fi Grid', family: "'Wallpoet', display", type: 'display', isPro: true },
  { name: 'Shadow Jacques', family: "'Jacques Francois Shadow', serif", type: 'display', isPro: true },
  { name: 'Victorian Shadow', family: "'Vast Shadow', display", type: 'display', isPro: true },
  { name: 'Antique Glass', family: "'Glass Antiqua', display", type: 'display', isPro: true },
  { name: 'Classic Calligraphy', family: "'Fondamento', cursive", type: 'handwriting', isPro: true },
  { name: 'Lucky Clover', family: "'Irish Grover', display", type: 'display', isPro: true },
  { name: 'Modern Lexend', family: "'Lexend', sans-serif", type: 'sans', isPro: true },
  { name: 'Simple Questrial', family: "'Questrial', sans-serif", type: 'sans', isPro: true },
  { name: 'Josefin Elegant', family: "'Josefin Sans', sans-serif", type: 'sans', isPro: true },
  { name: 'Urbanist Clean', family: "'Urbanist', sans-serif", type: 'sans', isPro: true },
  { name: 'Kumbh Geometric', family: "'Kumbh Sans', sans-serif", type: 'sans', isPro: true },
  { name: 'Lustria Serif', family: "'Lustria', serif", type: 'serif', isPro: true },
  { name: 'Editorial Spectral', family: "'Spectral', serif", type: 'serif', isPro: true },
  { name: 'Crimson Premium', family: "'Crimson Pro', serif", type: 'serif', isPro: true },
  { name: 'Alice Classic', family: "'Alice', serif", type: 'serif', isPro: true },
  { name: 'Academic Cardo', family: "'Cardo', serif", type: 'serif', isPro: true },
  { name: 'Chunky Bagel', family: "'Bagel Fat One', display", type: 'display', isPro: true },
  { name: 'Tactical Stencil', family: "'Black Ops One', display", type: 'display', isPro: true },
  { name: 'Speed Faster', family: "'Faster One', display", type: 'display', isPro: true },
  { name: 'Glitch Megrim', family: "'Megrim', display", type: 'display', isPro: true },
  { name: 'Cyber Orbitron', family: "'Orbitron', sans-serif", type: 'display', isPro: true },
  { name: 'Pirate Display', family: "'Pirata One', display", type: 'display', isPro: true },
  { name: 'Stencil Classic', family: "'Stardos Stencil', display", type: 'display', isPro: true },
];

export const THEMES: Theme[] = [
  {
    id: 'animated-nodus-official',
    name: 'Nodus Official',
    backgroundClass: 'bg-black',
    buttonClass: 'bg-white text-[#051a05] border-2 border-white font-black uppercase tracking-[0.2em] text-[12px] rounded-none shadow-[6px_6px_0_rgba(255,255,255,0.1)]',
    textClass: 'text-white',
    avatarBorder: 'border-white border-[3px] shadow-[10px_10px_0_rgba(255,255,255,0.05)]',
    isPro: true,
    solidColor: '#051a05',
    buttonHex: '#ffffff',
    category: 'animated'
  },
  {
    id: 'iridescence',
    name: 'Iridescence',
    backgroundClass: 'bg-black',
    buttonClass: 'bg-white/10 backdrop-blur-xl text-white border border-white/20 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] hover:bg-white/20 transition-all rounded-3xl font-bold uppercase tracking-tight',
    textClass: 'text-white',
    avatarBorder: 'border-white/50 border-4 shadow-2xl',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'animated'
  },
  {
    id: 'prismatic-burst',
    name: 'Prismatic Burst',
    backgroundClass: 'bg-black',
    buttonClass: 'bg-white/10 backdrop-blur-xl text-white border border-white/20 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] hover:bg-white/20 transition-all rounded-3xl font-bold uppercase tracking-tight',
    textClass: 'text-white',
    avatarBorder: 'border-white/50 border-4 shadow-2xl',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'animated'
  },
  {
    id: 'beams',
    name: 'Beams',
    backgroundClass: 'bg-black',
    buttonClass: 'bg-white/10 backdrop-blur-xl text-white border border-white/20 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] hover:bg-white/20 transition-all rounded-3xl font-bold uppercase tracking-tight',
    textClass: 'text-white',
    avatarBorder: 'border-white/50 border-4 shadow-2xl',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'animated'
  },
  {
    id: 'silk',
    name: 'Silk',
    backgroundClass: 'bg-[#7B7481]',
    buttonClass: 'bg-white/10 backdrop-blur-xl text-white border border-white/20 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] hover:bg-white/20 transition-all rounded-3xl font-bold uppercase tracking-tight',
    textClass: 'text-white',
    avatarBorder: 'border-white/50 border-4 shadow-2xl',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'animated'
  },
  {
    id: 'gradient-sunset-horizon',
    name: 'Sunset Horizon',
    backgroundClass: 'bg-gradient-to-br from-[#ff512f] to-[#dd2476]',
    buttonClass: 'bg-white/20 backdrop-blur-md text-white border border-white/30 rounded-2xl font-bold shadow-lg hover:bg-white/30 transition-all border-none',
    textClass: 'text-white',
    avatarBorder: 'border-white border-4 shadow-xl',
    isPro: false,
    category: 'gradient'
  },
  {
    id: 'gradient-deep-ocean',
    name: 'Deep Ocean',
    backgroundClass: 'bg-gradient-to-t from-[#0f2027] via-[#203a43] to-[#2c5364]',
    buttonClass: 'bg-cyan-500/10 backdrop-blur-xl text-cyan-50 border border-cyan-400/20 rounded-full font-medium tracking-wide shadow-[0_0_15px_rgba(34,211,238,0.2)]',
    textClass: 'text-slate-100',
    avatarBorder: 'border-cyan-400/50 border-2 shadow-2xl',
    isPro: false,
    category: 'gradient'
  },
  {
    id: 'gradient-midnight-neon',
    name: 'Midnight Neon',
    backgroundClass: 'bg-gradient-to-br from-[#000000] to-[#434343]',
    buttonClass: 'bg-transparent text-[#00f3ff] border-2 border-[#00f3ff] rounded-none font-black uppercase tracking-widest shadow-[4px_4px_0_#ff00ff] hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[6px_6px_0_#ff00ff] transition-all',
    textClass: 'text-[#ff00ff] font-black',
    avatarBorder: 'border-[#ff00ff] border-4 shadow-[0_0_20px_#00f3ff]',
    isPro: false,
    category: 'gradient'
  },
  {
    id: 'gradient-aurora-borealis',
    name: 'Aurora Borealis',
    backgroundClass: 'bg-gradient-to-r from-[#00c9ff] to-[#92fe9d]',
    buttonClass: 'bg-white text-slate-950 rounded-xl font-bold shadow-sm border border-slate-100/50 hover:shadow-md transition-shadow',
    textClass: 'text-white drop-shadow-md',
    avatarBorder: 'border-white/80 border-4 backdrop-blur-sm',
    isPro: false,
    category: 'gradient'
  },
  {
    id: 'gradient-royal-velvet',
    name: 'Royal Velvet',
    backgroundClass: 'bg-gradient-to-br from-[#4b1248] to-[#f0c27b]',
    buttonClass: 'bg-[#f0c27b] text-[#4b1248] rounded-none border-t-2 border-b-2 border-[#4b1248]/20 font-serif italic font-bold tracking-tight shadow-2xl',
    textClass: 'text-amber-50',
    avatarBorder: 'border-[#f0c27b] border-double border-8 p-1',
    isPro: false,
    category: 'gradient'
  },
  {
    id: 'music-synth-wave',
    name: 'Synthwave Night',
    backgroundClass: 'bg-[#0a001a]',
    buttonClass: 'bg-[#ff00ff]/10 backdrop-blur-xl text-white border border-[#ff00ff]/50 shadow-[0_0_20px_rgba(255,0,255,0.3)] hover:bg-[#ff00ff]/20 transition-all rounded-xl font-black uppercase tracking-widest',
    textClass: 'text-white',
    avatarBorder: 'border-[#00ffff] border-[3px] shadow-[0_0_20px_rgba(0,255,255,0.5)]',
    isPro: true,
    buttonHex: '#ff00ff',
    category: 'music'
  },
  {
    id: 'music-audio-pulse',
    name: 'Audio Pulse',
    backgroundClass: 'bg-[#020617]',
    buttonClass: 'bg-blue-600/20 backdrop-blur-lg text-white border border-blue-400/50 hover:bg-blue-600/30 rounded-full font-bold transition-all shadow-lg',
    textClass: 'text-white',
    avatarBorder: 'border-blue-500 border-2 shadow-glow',
    isPro: true,
    buttonHex: '#3b82f6',
    category: 'music'
  },
  {
    id: 'music-vinyl-groove',
    name: 'Vinyl Groove',
    backgroundClass: 'bg-[#121212]',
    buttonClass: 'bg-[#ff6b00]/10 backdrop-blur-md text-white border border-[#ff6b00]/30 hover:bg-[#ff6b00]/20 rounded-none font-medium tracking-tighter transition-all',
    textClass: 'text-white',
    avatarBorder: 'border-[#333] border-4 shadow-xl',
    isPro: true,
    buttonHex: '#ff6b00',
    category: 'music'
  },
  {
    id: 'music-electric-storm',
    name: 'Electric Storm',
    backgroundClass: 'bg-[#00040a]',
    buttonClass: 'bg-teal-500/10 backdrop-blur-2xl text-white border border-teal-400/40 hover:bg-teal-500/20 rounded-2xl font-black italic tracking-tight',
    textClass: 'text-white',
    avatarBorder: 'border-teal-400 border-[3px] shadow-[0_0_15px_rgba(45,212,191,0.4)]',
    isPro: true,
    buttonHex: '#2dd4bf',
    category: 'music'
  },
  {
    id: 'music-jazz-lounge',
    name: 'Jazz Lounge',
    backgroundClass: 'bg-[#1a0105]',
    buttonClass: 'bg-amber-900/40 backdrop-blur-xl text-amber-100 border border-amber-500/20 hover:bg-amber-900/60 rounded-sm font-serif italic transition-all shadow-2xl',
    textClass: 'text-amber-50',
    avatarBorder: 'border-amber-700/50 border-[5px] grayscale-[0.5]',
    isPro: true,
    buttonHex: '#fbbf24',
    category: 'music'
  },
  {
    id: 'music-acoustic-vibe',
    name: 'Acoustic Vibe',
    backgroundClass: 'bg-[#1c0d02]',
    buttonClass: 'bg-orange-900/20 backdrop-blur-lg text-orange-50 border border-orange-200/10 hover:bg-orange-900/30 rounded-3xl font-light tracking-wide',
    textClass: 'text-orange-50',
    avatarBorder: 'border-orange-200/20 border-2 rounded-full shadow-lg',
    isPro: true,
    buttonHex: '#f59e0b',
    category: 'music'
  },
  {
    id: 'music-lofi-beats',
    name: 'Lo-Fi Beats',
    backgroundClass: 'bg-[#2d1b4d]',
    buttonClass: 'bg-white/5 backdrop-blur-2xl text-purple-100 border border-white/10 hover:bg-white/10 rounded-2xl font-medium tracking-normal transition-all',
    textClass: 'text-purple-50',
    avatarBorder: 'border-purple-300/30 border-4 shadow-inner',
    isPro: true,
    buttonHex: '#ff9ffc',
    category: 'music'
  },
  {
    id: 'music-pop-star',
    name: 'Pop Star',
    backgroundClass: 'bg-[#ec4899]',
    buttonClass: 'bg-black text-white hover:bg-slate-900 rounded-full font-black uppercase tracking-tighter px-8 shadow-[0_10px_0_#db2777]',
    textClass: 'text-white',
    avatarBorder: 'border-white border-[6px] shadow-2xl skew-x-2',
    isPro: true,
    buttonHex: '#000000',
    category: 'music'
  },
  {
    id: 'music-techno-core',
    name: 'Techno Core',
    backgroundClass: 'bg-black',
    buttonClass: 'bg-[#00ff41]/5 backdrop-blur-md text-[#00ff41] border border-[#00ff41]/40 hover:bg-[#00ff41]/20 rounded-none font-mono text-xs uppercase tracking-[0.5em]',
    textClass: 'text-[#00ff41]',
    avatarBorder: 'border-[#00ff41] border-2 shadow-[0_0_10px_#00ff41]',
    isPro: true,
    buttonHex: '#00ff41',
    category: 'music'
  },
  {
    id: 'music-classical-flow',
    name: 'Classical Flow',
    backgroundClass: 'bg-[#f8f5f0]',
    buttonClass: 'bg-white text-slate-900 border-2 border-[#d4af37] hover:bg-[#fcfaf7] rounded-none font-serif uppercase tracking-[0.2em] shadow-sm',
    textClass: 'text-[#8b7355]',
    avatarBorder: 'border-[#d4af37] border-double border-4 shadow-inner',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'music'
  },
  {
    id: 'creative-pixel',
    name: 'Retro Vibe',
    backgroundClass: 'bg-[#2d1b4e]',
    buttonClass: 'bg-[#ff71ce] text-white hover:bg-[#ff71ce]/90 rounded-none font-black uppercase tracking-normal shadow-[4px_4px_0_#05d9e8]',
    textClass: 'text-[#01cdfe] font-bold uppercase',
    avatarBorder: 'border-[#b967ff] border-4 [image-rendering:pixelated] shadow-xl',
    isPro: true,
    buttonHex: '#ff71ce',
    category: 'creative'
  },
  {
    id: 'kawaii-clouds',
    name: 'Nuvem Doce',
    backgroundClass: 'bg-[#ffedfa]',
    solidColor: '#ffedfa',
    buttonClass: 'bg-white text-slate-900 hover:bg-white/90 rounded-full font-bold shadow-lg border-2 border-slate-100 px-8',
    textClass: 'text-[#ffb7e1] font-black',
    avatarBorder: 'border-[#ffb7e1] border-4 shadow-xl mb-4',
    isPro: true,
    buttonHex: '#ffb7e1',
    category: 'kawaii'
  },
  {
    id: 'kawaii-stars',
    name: 'Estrela Feliz',
    backgroundClass: 'bg-[#f3e8ff]',
    solidColor: '#f3e8ff',
    buttonClass: 'bg-[#fde047] text-slate-900 hover:bg-[#facc15] rounded-3xl font-black shadow-[0_4px_0_#ca8a04] px-8',
    textClass: 'text-[#8b5cf6] font-black uppercase tracking-wider',
    avatarBorder: 'border-[#fde047] border-4 shadow-lg',
    isPro: true,
    buttonHex: '#fde047',
    category: 'kawaii'
  },
  {
    id: 'kawaii-garden',
    name: 'Jardim Fofo',
    backgroundClass: 'bg-[#f0fdf4]',
    solidColor: '#f0fdf4',
    buttonClass: 'bg-[#f472b6] text-white hover:bg-[#ec4899] rounded-full font-bold shadow-md px-10 border-b-4 border-[#be185d]',
    textClass: 'text-[#166534] font-medium',
    avatarBorder: 'border-[#facc15] border-8 p-1 bg-white shadow-2xl',
    isPro: true,
    buttonHex: '#f472b6',
    category: 'kawaii'
  },
  {
    id: 'kawaii-peach',
    name: 'Sonho de Pêssego',
    backgroundClass: 'bg-[#fff1f2]',
    solidColor: '#fff1f2',
    buttonClass: 'bg-white text-slate-900 border-2 border-[#fda4af] hover:bg-white rounded-3xl font-bold italic',
    textClass: '#be123c',
    avatarBorder: 'border-[#fda4af] border-4 shadow-inner',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'kawaii'
  },
  {
    id: 'kawaii-milk',
    name: 'Leite e Mel',
    backgroundClass: 'bg-[#fffbeb]',
    solidColor: '#fffbeb',
    buttonClass: 'bg-white text-slate-900 hover:bg-slate-50 rounded-xl font-black shadow-sm border border-[#fde68a]',
    textClass: 'text-[#92400e] font-light uppercase tracking-widest',
    avatarBorder: 'border-white border-8 shadow-sm p-1 bg-amber-50',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'kawaii'
  },
  {
    id: 'kawaii-rainbow',
    name: 'Arco-Íris Pastel',
    backgroundClass: 'bg-[#f0f9ff]',
    solidColor: '#f0f9ff',
    buttonClass: 'bg-gradient-to-r from-[#fecaca] via-[#fef08a] to-[#bae6fd] text-slate-900 hover:opacity-90 rounded-full font-black px-12 shadow-inner',
    textClass: 'text-slate-500 font-bold',
    avatarBorder: 'border-white border-4 shadow-xl rounded-full',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'kawaii'
  },
  {
    id: 'kawaii-jelly',
    name: 'Jelly Bouncy',
    backgroundClass: 'bg-[#ecfeff]',
    solidColor: '#ecfeff',
    buttonClass: 'bg-[#818cf8] text-white hover:bg-[#6366f1] rounded-2xl font-black shadow-[0_8px_0_#4338ca] active:translate-y-1 active:shadow-none transition-all',
    textClass: 'text-[#1e1b4b] font-black',
    avatarBorder: 'border-[#22d3ee] border-[10px] shadow-2xl',
    isPro: true,
    buttonHex: '#818cf8',
    category: 'kawaii'
  },
  {
    id: 'kawaii-bakery',
    name: 'Padaria Kawaii',
    backgroundClass: 'bg-[#fff7ed]',
    solidColor: '#fff7ed',
    buttonClass: 'bg-[#fdba74] text-slate-950 hover:bg-[#fb923c] rounded-lg font-bold shadow-[4px_4px_0_#9a3412] px-8',
    textClass: 'text-[#9a3412] font-mono',
    avatarBorder: 'border-[#9a3412] border-2 p-2 bg-orange-50',
    isPro: true,
    buttonHex: '#fdba74',
    category: 'kawaii'
  },
  {
    id: 'kawaii-space',
    name: 'Astro Hamster',
    backgroundClass: 'bg-[#0f172a]',
    solidColor: '#0f172a',
    buttonClass: 'bg-white/10 backdrop-blur-md text-white border border-white/20 hover:bg-white/20 rounded-full font-medium tracking-widest',
    textClass: 'text-slate-300 font-thin italic',
    avatarBorder: 'border-white/20 border-2 rounded-full shadow-[0_0_15px_white]',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'kawaii'
  },
  {
    id: 'kawaii-matcha',
    name: 'Matcha Relax',
    backgroundClass: 'bg-[#f0fdf4]',
    solidColor: '#f0fdf4',
    buttonClass: 'bg-[#22c55e]/10 backdrop-blur-3xl text-[#166534] border-2 border-[#22c55e]/20 hover:bg-[#22c55e]/20 rounded-none font-bold tracking-widest px-10',
    textClass: 'text-[#166534] font-light italic',
    avatarBorder: 'border-[#4ade80] border-4 shadow-2xl',
    isPro: true,
    buttonHex: '#4ade80',
    category: 'kawaii'
  },
  {
    id: 'kawaii-sakura',
    name: 'Sakura Dreams',
    backgroundClass: 'bg-[#fff5f7]',
    solidColor: '#fff5f7',
    buttonClass: 'bg-white text-slate-950 hover:bg-white rounded-full font-bold shadow-[0_4px_12px_rgba(255,183,197,0.2)] border border-[#ffb7c5]/30 px-10 transition-all duration-300',
    textClass: 'text-[#d48191] font-bold tracking-tight',
    avatarBorder: 'border-white border-8 shadow-2xl p-0.5 bg-gradient-to-br from-[#ffb7c5]/20 to-transparent',
    isPro: true,
    buttonHex: '#ffffff',
    category: 'kawaii'
  }
];

export const SOCIAL_NETWORKS = [
  // Redes Sociais Gerais
  { id: 'custom', name: 'Link Personalizado', icon: LinkIcon, baseUrl: '', placeholder: 'https://seu-site.com' },
  { id: 'instagram', name: 'Instagram', icon: SiInstagram, baseUrl: 'https://instagram.com/', placeholder: '@usuario' },
  { id: 'facebook', name: 'Facebook', icon: SiFacebook, baseUrl: 'https://facebook.com/', placeholder: 'usuario' },
  { id: 'twitter', name: 'X (Twitter)', icon: SiX, baseUrl: 'https://x.com/', placeholder: '@usuario' },
  { id: 'tiktok', name: 'TikTok', icon: SiTiktok, baseUrl: 'https://tiktok.com/@', placeholder: '@usuario' },
  { id: 'threads', name: 'Threads', icon: SiThreads, baseUrl: 'https://threads.net/@', placeholder: '@usuario' },
  { id: 'linkedin', name: 'LinkedIn', icon: SiLinkedin, baseUrl: 'https://linkedin.com/in/', placeholder: 'usuario' },
  { id: 'whatsapp', name: 'WhatsApp', icon: SiWhatsapp, baseUrl: 'https://wa.me/', placeholder: '55999999999' },
  { id: 'telegram', name: 'Telegram', icon: SiTelegram, baseUrl: 'https://t.me/', placeholder: 'usuario' },

  // Vídeo / Streaming
  { id: 'youtube', name: 'YouTube', icon: SiYoutube, baseUrl: 'https://youtube.com/@', placeholder: '@canal' },
  { id: 'twitch', name: 'Twitch', icon: SiTwitch, baseUrl: 'https://twitch.tv/', placeholder: 'usuario' },
  { id: 'vimeo', name: 'Vimeo', icon: SiVimeo, baseUrl: 'https://vimeo.com/', placeholder: 'usuario' },

  // Música / Áudio
  { id: 'spotify', name: 'Spotify', icon: SiSpotify, baseUrl: 'https://open.spotify.com/user/', placeholder: 'usuario' },
  { id: 'soundcloud', name: 'SoundCloud', icon: SiSoundcloud, baseUrl: 'https://soundcloud.com/', placeholder: 'usuario' },
  { id: 'applemusic', name: 'Apple Music', icon: SiApplemusic, baseUrl: 'https://music.apple.com/profile/', placeholder: 'usuario' },

  // Profissional / Portfólio
  { id: 'github', name: 'GitHub', icon: SiGithub, baseUrl: 'https://github.com/', placeholder: 'usuario' },
  { id: 'behance', name: 'Behance', icon: SiBehance, baseUrl: 'https://behance.net/', placeholder: 'usuario' },
  { id: 'dribbble', name: 'Dribbble', icon: SiDribbble, baseUrl: 'https://dribbble.com/', placeholder: 'usuario' },
  { id: 'pinterest', name: 'Pinterest', icon: SiPinterest, baseUrl: 'https://pinterest.com/', placeholder: 'usuario' },

  // Games / Comunidades
  { id: 'discord', name: 'Discord', icon: SiDiscord, baseUrl: 'https://discord.gg/', placeholder: 'convite' },
  { id: 'steam', name: 'Steam', icon: SiSteam, baseUrl: 'https://steamcommunity.com/id/', placeholder: 'usuario' },

  // Vendas / Monetização
  { id: 'shopee', name: 'Shopee', icon: SiShopee, baseUrl: 'https://shopee.com.br/', placeholder: 'loja' },
  { id: 'amazon', name: 'Amazon Store', icon: SiAmazon, baseUrl: 'https://amazon.com/shop/', placeholder: 'storefront' },

  // Contato
  { id: 'email', name: 'Email', icon: Mail, baseUrl: 'mailto:', placeholder: 'seu@email.com' },
  { id: 'site', name: 'Site / Blog', icon: Globe, baseUrl: 'https://', placeholder: 'seusite.com' },
  { id: 'telefone', name: 'Telefone', icon: Phone, baseUrl: 'tel:', placeholder: '55999999999' },
];
